###########################
# Deployment
###########################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api-container
          image: changxu1998/sp22-cs411-team007-xgtc_api:latest
          ports:
            - containerPort: 8000
          command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
          env:
            - name: DJANGO_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: DJANGO_ENV
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: SECRET_KEY
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: DEBUG
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_IP
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: MYSQL_IP               

---
###########################
# Cluster IP Service
###########################
apiVersion: v1
kind: Service
metadata:
  name: api-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: api
  ports:
    - port: 8000
      targetPort: 8000