# Generated by Django 4.0.3 on 2022-04-03 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('airlineID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('airlineName', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airportID', models.AutoField(primary_key=True, serialize=False)),
                ('airportName', models.CharField(max_length=255)),
                ('airportCity', models.CharField(max_length=255)),
                ('airportCountry', models.CharField(max_length=255)),
                ('IATA', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FlightRoute',
            fields=[
                ('flightRouteID', models.AutoField(primary_key=True, serialize=False)),
                ('sourceAirport', models.CharField(max_length=255)),
                ('destinationAirport', models.CharField(max_length=255)),
                ('stops', models.IntegerField()),
                ('equipment', models.CharField(blank=True, default='', max_length=255)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.airline')),
                ('destinationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationID_id', to='flight.airport')),
                ('sourceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceID_id', to='flight.airport')),
            ],
        ),
        migrations.CreateModel(
            name='UserFlight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review', models.CharField(blank=True, default='', max_length=255)),
                ('flightRouteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flightroute')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
